/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConvertDialog.java
 *
 * Created on Jul 14, 2010, 12:30:51 PM
 */
package com.petroguia.ui;

import com.petroguia.model.*;
import java.awt.Color;
import javax.swing.*;
import java.util.*;

/**
 *
 * @author hb47537
 */
public class ConvertDialog extends javax.swing.JDialog {

   
    /** Creates new form ConvertDialog */
    public ConvertDialog( UInterface ui) {
        super(ui.getMainWindow());   

        initComponents();
        //this.jComboBox1.
        try {
            DefaultComboBoxModel m = new DefaultComboBoxModel(ModelAcess.fetchConversionTypes());
            jComboBox1.setModel(m);
            jComboBox1.setSelectedIndex(0);
            outTF.setEditable(false);
            //this.getContentPane().setBackground((new java.awt.Color(178, 204, 188)));
            this.getContentPane().setSize(414, 323);
            int w = getContentPane().getSize().width;
            int h = getContentPane().getSize().height;
            int x = (ui.getMainWindowWidth() - w) / 2;
            int y = (ui.getMainWindowHeight() - h) / 2;

            this.setLocation(x, y);
            ComponentMover cm = new ComponentMover(this, this);

            this.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Erro ao tentar abrir janela para conversão", "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        inTF = new javax.swing.JTextField();
        outTF = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Conversor");
        setBackground(new java.awt.Color(153, 204, 255));
        setModal(true);
        setResizable(false);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setAlignmentX(0.0F);
        jPanel2.setAlignmentY(0.0F);
        jPanel2.setPreferredSize(new java.awt.Dimension(42, 662));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel1.setText("Selecione o tipo de unidade que deseja converter");

        jComboBox1.setFont(new java.awt.Font("Arial", 0, 12));
        jComboBox1.setBorder(null);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel2.setText("De");

        jComboBox2.setFont(new java.awt.Font("Arial", 0, 12));
        jComboBox2.setBorder(null);
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel3.setText("Para");

        jComboBox3.setFont(new java.awt.Font("Arial", 0, 12));
        jComboBox3.setBorder(null);
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        inTF.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        inTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inTFKeyReleased(evt);
            }
        });

        outTF.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(outTF, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(inTF, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(1, 1, 1)
                .addComponent(inTF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel3)
                .addGap(1, 1, 1)
                .addComponent(outTF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jToggleButton1.setBackground(new java.awt.Color(178, 204, 188));
        jToggleButton1.setText("X");
        jToggleButton1.setBorder(null);
        jToggleButton1.setBorderPainted(false);
        jToggleButton1.setContentAreaFilled(false);
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(378, Short.MAX_VALUE)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToggleButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        try {
            String[] itens = ModelAcess.fetchConversionDescriptions((String) jComboBox1.getSelectedItem());

            DefaultComboBoxModel m =
                    new DefaultComboBoxModel(itens);
            jComboBox2.setModel(m);
            jComboBox2.setSelectedIndex(0);
            DefaultComboBoxModel m2 = new DefaultComboBoxModel(itens);
            jComboBox3.setModel(m2);
            jComboBox3.setSelectedIndex(0);

            this.inTF.setText("");
            this.outTF.setText("");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Erro ao tentar abrir tipos de conversão", "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        convert();
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        convert();
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void inTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inTFKeyReleased
        convert();
    }//GEN-LAST:event_inTFKeyReleased


    private void convert(){
        try {
            String texto = this.inTF.getText();
            if ((texto != null) && (!texto.equals(""))) {
                
                    String from = (String) jComboBox2.getSelectedItem();
                    String to = (String) jComboBox3.getSelectedItem();

                    StringTokenizer tok = new StringTokenizer(texto, ",");
                    texto = tok.nextToken();
                    if (tok.hasMoreTokens()) {
                        texto = texto + "." + tok.nextToken();
                    }
                    double in = Double.parseDouble(texto);
                    double result = 0.0;
                    if( from.equals(to)){
                        result = in;
                    }
                    else{
                        Formula formula = ModelAcess.buildConversionFormula(from, to);

                        //fetch the formulas parameters
                        Iterator it = formula.getinParameters().iterator();
                        FormulaParameter inParam = (FormulaParameter) it.next();
                        FormulaParameter outParam = formula.getoutParameter();

                        //define the unique in param value
                        inParam.setValue(in);
                        String unit = (String)inParam.getUnits().iterator().next();
                        //define the unique in param unit. In this case the only in param unit.
                        inParam.setCurrentUnit(unit);
                        LinkedList<FormulaParameter> lista =
                                new LinkedList<FormulaParameter>();
                        lista.add(inParam);

                        //define the current unit, in this case the same outparam unit
                        unit = (String)outParam.getUnits().iterator().next();
                        outParam.setCurrentUnit(unit);
                        outParam = formula.calculate(lista, outParam);
                        result = outParam.getValue();
                    }
                    
                    String output = String.valueOf(result);
                    tok = new StringTokenizer(output, ".");
                    output = tok.nextToken();
                    if (tok.hasMoreTokens()) {
                        output = output + "," + tok.nextToken();
                    }
                    this.outTF.setText(output);

                
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Erro ao tentar executar a conversão", "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField inTF;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField outTF;
    // End of variables declaration//GEN-END:variables
}
