/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConvertDialog.java
 *
 * Created on Jul 14, 2010, 12:30:51 PM
 */
package com.petroguia.ui;

import com.petroguia.model.*;
import java.awt.Color;
import javax.swing.*;
import java.util.*;


/**
 *
 * @author hb47537
 */
public class FormulaDialog extends javax.swing.JDialog {

    private Formula formula;
    private Collection inList = null;
    private FormulaParameter outParam = null;


    /** Creates new form ConvertDialog */
    public FormulaDialog( UInterface ui, Page page) {
        super(ui.getMainWindow());

        initComponents();
        //this.jComboBox1.
        //Object[] itens = {Formula.FORMULAS.values()};
       try{
        if( page == null){
            DefaultComboBoxModel m = new DefaultComboBoxModel(ModelAcess.fetchFormulaNames());
            jComboBox1.setModel(m);
            jComboBox1.setSelectedIndex(0);

        }
        else{
           DefaultComboBoxModel m = new DefaultComboBoxModel(new String[]{page.getName()});
           jComboBox1.setModel(m);
           jComboBox1.setSelectedItem(0);
           /*if( form == Formula.FORMULAS.Pressão_Hidrostática)
               jComboBox1.setSelectedIndex(0);
           else jComboBox1.setSelectedIndex(1);*/
        }
        }
       catch(Exception e){
           e.printStackTrace();
           JOptionPane.showMessageDialog(this, e.getMessage());
       }

        initComboBox1();

        //this.getContentPane().setBackground((new java.awt.Color(178, 204, 188)));
        this.getContentPane().setSize(414, 323);
        int w = getContentPane().getSize().width;
        int h = getContentPane().getSize().height;
        int x = (ui.getMainWindowWidth() - w) / 2;
        int y = (ui.getMainWindowHeight() - h) / 2;

        this.setLocation(x, y);
        ComponentMover cm = new ComponentMover(this, this);

        this.setVisible(true);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        inLabel1 = new javax.swing.JLabel();
        inLabel2 = new javax.swing.JLabel();
        cb1 = new javax.swing.JComboBox();
        cb2 = new javax.swing.JComboBox();
        cb3 = new javax.swing.JComboBox();
        calculateButton = new javax.swing.JToggleButton();
        inFT1 = new javax.swing.JTextField();
        inFT2 = new javax.swing.JTextField();
        outFT = new javax.swing.JTextField();
        inLabel3 = new javax.swing.JLabel();
        inFT3 = new javax.swing.JTextField();
        cb4 = new javax.swing.JComboBox();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Conversor");
        setBackground(new java.awt.Color(153, 204, 255));
        setModal(true);
        setResizable(false);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setAlignmentX(0.0F);
        jPanel2.setAlignmentY(0.0F);
        jPanel2.setPreferredSize(new java.awt.Dimension(42, 662));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel1.setText("Selecione o valor que deseja calcular");

        jComboBox1.setFont(new java.awt.Font("Arial", 0, 12));
        jComboBox1.setBorder(null);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        inLabel1.setFont(new java.awt.Font("Arial", 0, 12));
        inLabel1.setText("Valor da Densidade do fluido");

        inLabel2.setFont(new java.awt.Font("Arial", 0, 12));
        inLabel2.setText("Valor da Profundidade");

        cb1.setFont(new java.awt.Font("Arial", 0, 12));
        cb1.setBorder(null);
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });

        cb2.setFont(new java.awt.Font("Arial", 0, 12));
        cb2.setBorder(null);
        cb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb2ActionPerformed(evt);
            }
        });

        cb3.setFont(new java.awt.Font("Arial", 0, 12));
        cb3.setBorder(null);
        cb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb3ActionPerformed(evt);
            }
        });

        calculateButton.setForeground(new java.awt.Color(0, 51, 153));
        calculateButton.setText("Calcular");
        calculateButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });

        outFT.setEditable(false);

        inLabel3.setFont(new java.awt.Font("Arial", 0, 12));
        inLabel3.setText("Valor da Profundidade");

        cb4.setFont(new java.awt.Font("Arial", 0, 12));
        cb4.setBorder(null);
        cb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBox1, 0, 462, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(calculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                        .addComponent(outFT, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inFT1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inFT2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inFT3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(inFT1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(inLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(inFT2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(inLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inFT3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outFT, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jToggleButton1.setBackground(new java.awt.Color(178, 204, 188));
        jToggleButton1.setText("X");
        jToggleButton1.setBorder(null);
        jToggleButton1.setBorderPainted(false);
        jToggleButton1.setContentAreaFilled(false);
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToggleButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initComboBox1(){
        inFT1.setText("");
        inFT2.setText("");
        inFT3.setText("");
        outFT.setText("");

        formula = ModelAcess.buildFormula((String) jComboBox1.getSelectedItem());

        try {
            inList = formula.getinParameters();

            Iterator it = inList.iterator();
            FormulaParameter param = (FormulaParameter) it.next();

            inLabel1.setText(param.getName());
            inFT1.setVisible(true);
            cb1.setVisible(true);
            Object[] units = param.getUnits().toArray();
            cb1.setModel(new javax.swing.DefaultComboBoxModel(units));

            outParam = formula.getoutParameter();
            units = outParam.getUnits().toArray();
            cb3.setModel(new javax.swing.DefaultComboBoxModel(units));
            cb2.setVisible(false);
            cb4.setVisible(false);

            if (inList.size() > 1) {
                param = (FormulaParameter) it.next();

                inLabel2.setText(param.getName());
                inFT2.setVisible(true);
                cb2.setVisible(true);
                units = param.getUnits().toArray();
                cb2.setModel(new javax.swing.DefaultComboBoxModel(units));
            } else {
                inLabel2.setText("");
                inFT2.setVisible(false);
                cb2.setVisible(false);
            }

            if (inList.size() > 2) {
                param = (FormulaParameter) it.next();

                inLabel3.setText(param.getName());
                inFT3.setVisible(true);
                cb4.setVisible(true);
                units = param.getUnits().toArray();
                cb4.setModel(new javax.swing.DefaultComboBoxModel(units));
            } else {
                inLabel3.setText("");
                inFT3.setVisible(false);
                cb4.setVisible(false);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }


    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
          initComboBox1();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        String valor1 = inFT1.getText();
        if ((valor1 != null) && (!valor1.equals(""))) {
            
        calculate();
        }
    }//GEN-LAST:event_cb1ActionPerformed

    private void cb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb2ActionPerformed
        String valor1 = inFT2.getText();
        if ((valor1 != null) && (!valor1.equals(""))) {

        calculate();
        }
    }//GEN-LAST:event_cb2ActionPerformed

    private void cb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb3ActionPerformed
        String valor1 = inFT1.getText();
        if ((valor1 != null) && (!valor1.equals(""))) {
             calculate();
        }
    }//GEN-LAST:event_cb3ActionPerformed

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
        String valor1 = inFT1.getText();
        if ((valor1 == null) || (valor1.equals(""))) {
            JOptionPane.showMessageDialog(this, "Entre com um valor");
        } else {
        calculate();
        }
    }//GEN-LAST:event_calculateButtonActionPerformed

    private void cb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb4ActionPerformed
        String valor1 = inFT3.getText();
        if ((valor1 != null) && (!valor1.equals(""))) {

        calculate();
        }
    }//GEN-LAST:event_cb4ActionPerformed


    private void calculate(){
            String valor1 = inFT1.getText();
            String valor2 = inFT2.getText();
            String valor3 = inFT3.getText();
            
            Iterator it = inList.iterator();
            FormulaParameter param1 = (FormulaParameter)it.next();
            FormulaParameter param2 = null;
            FormulaParameter param3 = null;
            if( it.hasNext())
                param2 = (FormulaParameter)it.next();
            if( it.hasNext())
                param3 = (FormulaParameter)it.next();

            LinkedList<FormulaParameter> resultList = new LinkedList<FormulaParameter>();
            param1.setCurrentUnit( (String)cb1.getSelectedItem() );
            outParam.setCurrentUnit((String)cb3.getSelectedItem() );
            StringTokenizer tok = new StringTokenizer(valor1, ",");
            valor1 = tok.nextToken();
            if (tok.hasMoreTokens()) {
                valor1 = valor1 + "." + tok.nextToken();
            }
            double d = Double.parseDouble(valor1);
            param1.setValue(d);
            resultList.add(param1);

            try {


                if ((valor2 != null) && (!valor2.equals(""))) {
                    param2.setCurrentUnit( (String)cb2.getSelectedItem() );
                    tok = new StringTokenizer(valor2, ",");
                    valor2 = tok.nextToken();
                    if (tok.hasMoreTokens()) {
                        valor2 = valor2 + "." + tok.nextToken();
                    }

                    d = Double.parseDouble(valor2);
                    param2.setValue(d);
                    resultList.add(param2);
                }
                if ((valor3 != null) && (!valor3.equals(""))) {
                    param3.setCurrentUnit( (String)cb4.getSelectedItem() );
                    tok = new StringTokenizer(valor3, ",");
                    valor3 = tok.nextToken();
                    if (tok.hasMoreTokens()) {
                        valor3 = valor3 + "." + tok.nextToken();
                    }

                    d = Double.parseDouble(valor3);
                    param3.setValue(d);
                    resultList.add(param3);
                }

                outParam = formula.calculate(resultList, outParam);

                cb3.setSelectedItem(outParam.getCurrentUnit());
                String formatedResult = String.valueOf(outParam.getValue());
                tok = new StringTokenizer(formatedResult, ".");
                formatedResult = tok.nextToken();
                if (tok.hasMoreTokens()) {
                    formatedResult = formatedResult + "," + tok.nextToken();
                }


                this.outFT.setText(formatedResult);
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton calculateButton;
    private javax.swing.JComboBox cb1;
    private javax.swing.JComboBox cb2;
    private javax.swing.JComboBox cb3;
    private javax.swing.JComboBox cb4;
    private javax.swing.JTextField inFT1;
    private javax.swing.JTextField inFT2;
    private javax.swing.JTextField inFT3;
    private javax.swing.JLabel inLabel1;
    private javax.swing.JLabel inLabel2;
    private javax.swing.JLabel inLabel3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField outFT;
    // End of variables declaration//GEN-END:variables
}
